/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-telemetry_primaryheader_adder_1
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_TELEMETRY_PRIMARYHEADER_ADDER_1_API_H
#define INCLUDED_TELEMETRY_PRIMARYHEADER_ADDER_1_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_telemetry_primaryheader_adder_1_EXPORTS
#define TELEMETRY_PRIMARYHEADER_ADDER_1_API __GR_ATTR_EXPORT
#else
#define TELEMETRY_PRIMARYHEADER_ADDER_1_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_TELEMETRY_PRIMARYHEADER_ADDER_1_API_H */
