find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_TELEMETRY_PRIMARYHEADER_ADDER_1 gnuradio-telemetry_primaryheader_adder_1)

FIND_PATH(
    GR_TELEMETRY_PRIMARYHEADER_ADDER_1_INCLUDE_DIRS
    NAMES gnuradio/telemetry_primaryheader_adder_1/api.h
    HINTS $ENV{TELEMETRY_PRIMARYHEADER_ADDER_1_DIR}/include
        ${PC_TELEMETRY_PRIMARYHEADER_ADDER_1_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_TELEMETRY_PRIMARYHEADER_ADDER_1_LIBRARIES
    NAMES gnuradio-telemetry_primaryheader_adder_1
    HINTS $ENV{TELEMETRY_PRIMARYHEADER_ADDER_1_DIR}/lib
        ${PC_TELEMETRY_PRIMARYHEADER_ADDER_1_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-telemetry_primaryheader_adder_1Target.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_TELEMETRY_PRIMARYHEADER_ADDER_1 DEFAULT_MSG GR_TELEMETRY_PRIMARYHEADER_ADDER_1_LIBRARIES GR_TELEMETRY_PRIMARYHEADER_ADDER_1_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_TELEMETRY_PRIMARYHEADER_ADDER_1_LIBRARIES GR_TELEMETRY_PRIMARYHEADER_ADDER_1_INCLUDE_DIRS)
